version: '3.8'

services:
  app:
    build: .
    container_name: feedback_app
    env_file:
      - .env
    volumes:
      - ./:/app
      - db_data:/db/database
    ports:
      - "8000:8000"
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    env_file:
      - .env
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  db_data:
  n8n_data:
